const sub=new Map([
  ["tab", "tablet"],
  ["tabs", "tablet"],
  ["inj", "injection"],
  ["cap", "capsule"],
  ["caps", "capsule"],
  ["syrub", "syrup"],
  ["syr", "syrup"],
  ["susp", "suspension"],
  ["amp", "ampoule"],
  ["vial", "vial"],
  ["cream", "cream"],
  ["ointment", "ointment"],
  ["soln", "solution"],
  ["sol", "solution"],
  ["mg", "milligram"],
  ["ml", "millilitre"],
  ["gm", "gram"],
  ["gr", "gram"],
  ["pdr", "powder"],
  ["pdrs", "powder"],
  ["drp", "drops"],
  ["drps", "drops"],
  ["forte", "forte"],
  ["inj.", "injection"],
  ["tab.", "tablet"],
  ["cap.", "capsule"],
  ["syr.", "syrup"],
  ["vitc", "vitaminc"],
  ["vitamin c", "vitamin C"],
  ['ats','Antitetanusserum'],
  ["caf", "caffeine"],
  ["vitd", "vitamin D"],
  ["mantox", "mantoux test"],
])

export default sub;